#!/usr/bin/env bash
# should print the contents of the file `/etc/passwd`
#   should only print the username with user id and user home path

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
