#!/usr/bin/env bash
# should print the contents of the current directory in list format
#   should Only print the part of the name after the first dash

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
